config/routes.rb
Rails.application.routes.draw do
  devise_for :logins
  resources :friends
  get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :second, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, class:"form-label", for: "exampleFormControlInput1" %>
    <%= form.text_field :first_name, class:"form-control", for: "exampleFormControlInput1", placeholder: "Enter your given name"  %>
  </div>


  <div class="mb-3">
    <%= form.label :last_name, class:"form-label", for: "exampleFormControlInput1" %>
    <%= form.text_field :last_name, class:"form-control", for: "exampleFormControlInput1", placeholder: "Enter your family name" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class:"form-label", for: "exampleFormControlInput1" %>
    <%= form.text_field :email, class:"form-control", for: "exampleFormControlInput1", placeholder: "id@domain.com" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class:"form-label", for: "exampleFormControlInput1" %>
    <%= form.text_field :phone, class:"form-control", for: "exampleFormControlInput1", placeholder: "Enter Phonenumber" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, class:"form-label", for: "exampleFormControlInput1" %>
    <%= form.text_field :twitter, class:"form-control", for: "exampleFormControlInput1", placeholder: "@twitter_handle" %>
  </div>

  <div class="mb-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend,  class:"btn btn-light" %>
<%= link_to 'Back', friends_path,  class:"btn btn-light" %>

app/views/friends/index.html.erb
<table class="table table-striped table-hover table-bordered table-hover">
  <thead class = "table-dark"> 
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to 'Show', friend, class:"btn btn-light" %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend),  class:"btn btn-light" %></td>
        <td><%= button_to 'Delete', friend, method: :delete, :onclick => "return confirm('Are you sure you want to delete this entry?')",  class:"btn btn-light" %></td>
      </tr>
    <% end %>
      </tbody>
</table>


<br>
  <%= link_to 'New Friend', new_friend_path, class:"btn btn-light" %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path,  class:"btn btn-light" %>

app/views/friends/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @friend.first_name %> <%= @friend.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @friend.twitter %></h6>
    <p class="card-text"><%= @friend.phone %></p>
    <a href="mailto:someone@yoursite.com" class="card-link"><%= @friend.email %></a>
    <br><br>
    <%= link_to 'Edit', edit_friend_path(@friend),  class:"btn btn-light" %>
    <%= link_to 'Back', friends_path,  class:"btn btn-light" %>
    
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%=link_to 'Test_1', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
        	<%= link_to 'About Us', home_about_path, class:"nav-link" %>          
        </li>

        <li class="nav-item">
          <%= link_to 'Friend List', friends_path, class:"nav-link" %>        
        </li>
        
        <% if login_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_login_registration_path, class:"nav-link" %>            
          </li>

          <li class="nav-item">
            <%= link_to 'Sign out', destroy_login_session_path, class:"nav-link" %>            
          </li>          

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_login_registration_path, class:"nav-link" %>            
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_login_session_path, class:"nav-link" %>     
          </li>
        <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About Ruby </h1>

app/views/home/index.html.erb
<h1>Home_Page</h1>
<p>This is the landing page</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Test_1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = "container"> 
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %> 
      <% end %>

      <br/>
     <%= yield %>

   </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>
 